from textblob import TextBlob

text = '''Here is the most simple example of a sentence. The rest of the text is autogenerated. This gives the program some time to perform its computations and then tries to find the shortest possible possible sentence. Finally, let's look at the output that is used for the rest of the process.'''

blob = TextBlob(text)
blob.tags
blob.noun_phrases

for i in blob.sentences:
    print(i.sentiment.polarity)
