---
pipeline:
  name: histogram
description: A pipeline that creates histograms for images stored in the contour repository.
transform:
  cmd:
  - python3
  - "/histogram.py"
  image: svekars/contour-histogram:1.0
input:
  pfs:
    repo: contour
    glob: "/"

